# Packages 📦
Run the following cell to load all needed packages.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import copy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Data 📊
Lets get familiar with the data we will be working with. Start by loading the training data into a pandas Dataframe and extracting high level information.

In [3]:
df = pd.read_csv("../data/train.csv")
df.describe()

,MSSubClass,MSZoning,LotFrontage,LotArea,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,...,GarageFinish_Missing,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_N,PavedDrive_P,PavedDrive_Y,PoolQC_Ex,PoolQC_Fa,PoolQC_Gd,PoolQC_Missing
731,80,0.788356,73.0,9590,0.180137,0.026027,0.863014,0.989726,0.835616,0.044521,...,0,0,0,0,0,1,0,0,0,1
299,20,0.788356,80.0,14000,0.720548,0.034932,0.863014,0.989726,0.835616,0.497260,...,0,0,1,0,0,1,0,0,0,1
775,120,0.149315,32.0,4500,0.032192,0.033562,0.863014,0.989726,0.078082,0.497260,...,0,0,0,0,0,1,0,0,0,1
727,20,0.788356,64.0,7314,0.720548,0.102740,0.863014,0.989726,0.835616,0.497260,...,0,1,0,0,0,1,0,0,0,1
824,20,0.044521,81.0,11216,0.720548,0.058904,0.863014,0.989726,0.835616,0.497260,...,0,1,0,0,0,1,0,0,0,1

# Data 📊
- As we can observe from the result of the previous cell, some features are on a different scale than other features. This difference in scale makes it a ideal for us to normalize the data to bring all features to a small and common scale.
- Also, we can observe that some of the features are in a significantly higher scale than others. We will need to scale this features down before normalizing them. We will use *log* to scale these features down

# Feature & Label 🏷️
- Before scaling and normalizing the data, lets go ahead and split our feature data from our label data

In [92]:
y = df[["Id", "SalePrice"]]
X = df.drop(columns=["Id", "SalePrice"])

print(f"Label Dataset shape: {y.shape}")
print(f"Feature Dataset shape: {X.shape}")
y.head()
X.head()

Label Dataset shape: (1460, 2)
Feature Dataset shape: (1460, 79)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

# NaN Column Values 🚫
- Lets extract columns that have missing values. We will need to populate these columns with the appropriate data otherwise we will face issues when training the model.
- For this project, we will update **Null** values with the **median** ONLY for numerical columns.

In [93]:
na_columns = {col: i for i, col in enumerate(X.columns) if X[col].isna().any()}

print(f"\nAmount of columns with NaN values: {len(na_columns.keys())}")
print(f"\nColumns with NaN values: {na_columns.keys()}")

# Extracts columns from na_columns whose datatype is not numeric
nan_cols = {col: idx for col, idx in na_columns.items() if X[col].dtype == type(object)}
print(f"\nAmount of Non-numerical columns with Null values: {len(nan_cols.keys())}")
print(f"Columns of type object with null values: {nan_cols.keys()}")

# Extract numerical cols with Null values
num_cols_na = {col: idx for col, idx in na_columns.items() if nan_cols.get(col, False) is False}
print(f"\nAmount of numerical columns with Null values: {len(num_cols_na.keys())}")
print(f"Columns of type object with null values: {num_cols_na.keys()}")

# Extract the median for each column
na_cols_median_vals = {col: X[col].median() for col in num_cols_na.keys()}
print(na_cols_median_vals)

#Fill NaNs
for col in num_cols_na:
    X[col] = X[col].fillna(na_cols_median_vals[col])


# Fill cols with 'NA'
# > if previous logic does not work, try this: For non-numeric columns, populate NULL values with the most frequent used value
for col in nan_cols:
    X[col] = X[col].fillna("Missing")
    #col_counts = col_s.value_counts()
    #print(col_counts)

# Check for NaNs to ensure all columns are populated
na_columns = {col: i for i, col in enumerate(X.columns) if X[col].isna().any()}
print(f"\nColumns with Nulls: {len(na_columns.keys())}")
X.head()

Amount of columns with NaN values: 19

Columns with NaN values: dict_keys(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature'])

Amount of Non-numerical columns with Null values: 16
Columns of type object with null values: dict_keys(['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature'])

Amount of numerical columns with Null values: 3
Columns of type object with null values: dict_keys(['LotFrontage', 'MasVnrArea', 'GarageYrBlt'])
{'LotFrontage': np.float64(69.0), 'MasVnrArea': np.float64(0.0), 'GarageYrBlt': np.float64(1980.0)}

Columns with Nulls: 0

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,Inside,...,0,0,Missing,Missing,Missing,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,FR2,...,0,0,Missing,Missing,Missing,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,Inside,...,0,0,Missing,Missing,Missing,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,Corner,...,0,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,FR2,...,0,0,Missing,Missing,Missing,0,12,2008,WD,Normal

# Train & Validation Datasets 📈
- In this part of the notebook, we will normalize our dataset as well as splittling between between **train** and **validation** datasets.
- We need to remember that we have several columns that are categorical, so we need to encode these columns. We will **one-hot** encode **low-cardinality** columns and **frequency encode** for **moderate and high-cardinality** columns.
- For features that are on a larger scale than others, we will scale them down using **log** before normalizing them.
- For normalization, we are going to utilize scikit-learn **StandardScaler** which allows us to normalize our features with **z-score** normalization.

In [94]:
# Lets extract all numerical cols & non-numerical cols for later use
numerical_cols = [col for col in X.columns if X[col].dtype != type(object)]
categorical_cols = [col for col in X.columns if X[col].dtype == type(object)]

print(f"Feature dataset shape before encoding: {X.shape}")
# Lets frequency encode moderate and high cardinality columns, and one-hot encode low cardinality columns
for col in categorical_cols:
    num_of_categories = X[col].nunique()

    # Frequency encode if num of categories >= 5
    if num_of_categories >= 5:
        cat_frequencies = X[col].value_counts(normalize=True)
        X[col] = X[col].map(cat_frequencies)
    else: # one-hot encode all others
        one_hot_encoded = pd.get_dummies(X[col], prefix=col, dummy_na=False, dtype="uint8")
        X = pd.concat([X.drop(columns=[col]), one_hot_encoded], axis=1)
    
print(f"\nFeatue dataset shape after encoding: {X.shape}")

# Extract column names
column_names = X.columns

# Lets start by splittling our dataset into train and validation
print(f"\nFeatures shape before splitting: {X.shape}")
print(f"\nLabel shape before splitting: {y.shape}")
X_train, X_cv, y_train, y_cv = train_test_split(X, y, test_size=0.3, shuffle=True)

print(f"\nTrain Features shape: {X_train.shape}")
print(f"Train Labels shape: {y_train.shape}")
print(f"\nTrain Features shape: {X_cv.shape}")
print(f"Train Labels shape: {y_cv.shape}")

# Now that we splitted our Datasets into train and cv, lets go ahead and scale and normalize our features
# Start with the train dataset
cols_to_log = [col for col in numerical_cols if X[col].max() >= 500]
X_train_log = copy.deepcopy(X_train)

for col in cols_to_log:
    X_train_log[col] = X_train_log[col].map(lambda x: np.log1p(x))    

# Normalize train dataset with z-score
scaler = StandardScaler()
index = X_train_log.index
X_train_scaled = scaler.fit_transform(X_train_log) # numpy array
X_train_scaled_df = pd.DataFrame(X_train_scaled, index=index, columns=column_names)

# ***CV Dataset***
X_cv_log = copy.deepcopy(X_cv)

# Log scale the cv feature dataset
for col in cols_to_log:
    X_cv_log[col] = X_cv_log[col].map(lambda x: np.log1p(x))

# Normalize cv dataset with z-score
cv_index = X_cv_log.index
X_cv_scaled = scaler.transform(X_cv_log) # numpy array
X_cv_scaled_df = pd.DataFrame(X_cv_scaled, index=cv_index, columns=column_names)

# Uncomment X_train and comment X_cv for better visualization
# X_train_scaled_df.head() 
X_cv_scaled_df.head()

Feature dataset shape before encoding: (1460, 79)

Featue dataset shape after encoding: (1460, 109)

Features shape before splitting: (1460, 109)

Label shape before splitting: (1460, 2)

Train Features shape: (1022, 109)
Train Labels shape: (1022, 2)

Train Features shape: (438, 109)
Train Labels shape: (438, 2)

,MSSubClass,MSZoning,LotFrontage,LotArea,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,...,GarageFinish_Missing,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_N,PavedDrive_P,PavedDrive_Y,PoolQC_Ex,PoolQC_Fa,PoolQC_Gd,PoolQC_Missing
695,-0.871544,0.511203,-0.742685,0.826337,0.61541,-0.965601,0.406487,0.088823,0.440118,0.877404,...,-0.262750,-0.640043,1.221754,-0.269078,-0.155074,0.316398,-0.044281,-0.044281,-0.044281,0.076847
1231,0.786928,0.511203,0.012469,-0.313721,0.61541,1.980344,0.406487,0.088823,-2.326487,-1.862006,...,-0.262750,-0.640043,1.221754,-0.269078,-0.155074,0.316398,-0.044281,-0.044281,-0.044281,0.076847
1139,-0.634620,0.511203,1.333988,-0.074117,0.61541,-0.650527,0.406487,0.088823,0.440118,0.877404,...,-0.262750,-0.640043,1.221754,-0.269078,-0.155074,0.316398,-0.044281,-0.044281,-0.044281,0.076847
307,-0.160770,-1.821907,-0.034728,-0.265535,0.61541,-0.981355,-2.467867,0.088823,0.440118,-1.493159,...,3.805897,-0.640043,-0.818495,3.716395,-0.155074,-3.160577,-0.044281,-0.044281,-0.044281,0.076847
1047,-0.871544,0.511203,-0.601093,0.038202,0.61541,0.798815,0.406487,0.088823,0.440118,0.877404,...,-0.262750,-0.640043,1.221754,-0.269078,-0.155074,0.316398,-0.044281,-0.044281,-0.044281,0.076847